package cc.darhao.oexam.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseResult<M extends BaseResult<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setExamer(java.lang.Long examer) {
		set("examer", examer);
		return (M)this;
	}
	
	public java.lang.Long getExamer() {
		return getLong("examer");
	}

	public M setTime(java.util.Date time) {
		set("time", time);
		return (M)this;
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public M setTeamGrade(java.lang.Integer teamGrade) {
		set("team_grade", teamGrade);
		return (M)this;
	}
	
	public java.lang.Integer getTeamGrade() {
		return getInt("team_grade");
	}

	public M setStandardGrade(java.lang.Integer standardGrade) {
		set("standard_grade", standardGrade);
		return (M)this;
	}
	
	public java.lang.Integer getStandardGrade() {
		return getInt("standard_grade");
	}

	public M setExamee(java.lang.Long examee) {
		set("examee", examee);
		return (M)this;
	}
	
	public java.lang.Long getExamee() {
		return getLong("examee");
	}

}
