package cc.darhao.oexam.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setKei(java.lang.String kei) {
		set("kei", kei);
		return (M)this;
	}
	
	public java.lang.String getKei() {
		return getStr("kei");
	}

	public M setIsAdmin(java.lang.Integer isAdmin) {
		set("is_admin", isAdmin);
		return (M)this;
	}
	
	public java.lang.Integer getIsAdmin() {
		return getInt("is_admin");
	}

}
